### ISSUE TITLE
您好，这个小程序该怎么使用呢

### ISSUE THREAD

**Issue by GD-Slime** [jiahoo/Giwifi_crac#1]
是用了giwifi的充值接口吗？这样的话 是不是将其中的156xxxxxxxx改成我的手机号就可以使用？

**Comment by jiahoo** [comment]
是用的这个接口，但是不稳定。

**Comment by jiahoo** [comment]
> 是用了giwifi的充值接口吗？这样的话 是不是将其中的156xxxxxxxx改成我的手机号就可以使用？
> 
> 另外我看到您的认证用ip和我的一样，可能都是山科的，如果可以的话可以留一下联系方式吗
